export * from "./auth.model";
export * from "./base.model";
export * from "./discipline.model";
export * from "./icon.model";
export * from "./paginate.model";
export * from "./params.model";
export * from "./route.model";
export * from "./student.model";
export * from "./user.model";
